sudo: required
language: go

go:
  - 1.11.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - make dep

script:
  - make test
  - make build docker-build

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    else
      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin;
      make docker-push;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
