# test cmd:
# while true; do sleep 1; curl -sS -H "Host: podinfo.test" -H "x-subscription: trial"  http://35.198.122.99:30080|grep HOSTNAME;done
---
apiVersion: v1
kind: Service
metadata:
  name: green
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: green
      prefix: /
      host: podinfo.test
      service: green.default:9898
      weight: 50
      headers:
        X-Subscription: trial
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
  selector:
    app: green
---
apiVersion: v1
kind: Service
metadata:
  name: blue-trial
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: blue-trial
      prefix: /
      host: podinfo.test
      service: blue.default:9898
      headers:
        X-Subscription: trial
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
  selector:
    app: blue
