---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k9-cfg
  namespace: ide
data:
  gcp-clone.sh: |
    #!/usr/bin/env sh

    export PATH=/google-cloud-sdk/bin:$PATH
    git config --global credential.helper gcloud.sh
    git config --global user.email "dx+training@weave.works"
    git config --global user.name "k8s fan"

    git clone -b master $1
