---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: ide
  name: ide-workspace-data
  namespace: ide
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
