---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: ide
  name: ide
  namespace: ide
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: ide
  name: ide-cluster-view
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: ide
  name: ide-cluster-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ide-cluster-view
subjects:
- kind: ServiceAccount
  name: ide
  namespace: ide
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    name: ide
  name: ide-workspace-workspace-admin
  namespace: ide-workspace
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    name: ide
  name: ide-workspace-workspace-admin
  namespace: ide-workspace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ide-workspace-workspace-admin
subjects:
- kind: ServiceAccount
  name: ide
  namespace: ide
