---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ide
  name: ide
  namespace: ide
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: ide
  type: LoadBalancer
