{{- if .Values.externalServices -}}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ template "podinfo-istio.fullname" . }}-external-svcs
  labels:
    app: {{ template "podinfo-istio.fullname" . }}
    chart: {{ template "podinfo-istio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  {{- range .Values.externalServices }}
  - {{ . }}
  {{- end }}
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
{{- end }}