# Default values for loadtest.

image: stefanprodan/loadtest:latest

tests:
  - name: "blue"
    url: "https://canary.istio.weavedx.com/api/echo"
    cmd: "-h2 -m POST -d '{test: 1}' -H 'X-API-Version: 0.6.0' -c 50 -q 5"
  - name: "green"
    url: "https://canary.istio.weavedx.com/api/echo"
    cmd: "-h2 -m POST -d '{test: 2}' -H 'X-API-Version: 0.6.1' -c 10 -q 5"
