---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-store
  labels:
    app: podinfo-store
    version: "0.6"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
     app: podinfo-store
     version: "0.6"
  template:
    metadata:
      labels:
        app: podinfo-store
        version: "0.6"
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: podinfod
        image: docker.io/richardcase/podinfo:0.6.0
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 3
        command:
          - ./podinfo
          - -port=9898
          - -logLevel=debug
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
        env:
          - name: color
            value: "yellow"
          - name: message
            value: "Greetings from store yellow"
